# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAnketa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_created=True)),
                ('update_dt', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birthday', models.DateTimeField()),
                ('telephone', models.CharField(max_length=14)),
                ('passport_num', models.CharField(max_length=20)),
                ('score_bal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Predlogenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_created=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('start_rotate', models.DateTimeField()),
                ('end_rotate', models.DateTimeField()),
                ('name', models.CharField(max_length=254)),
                ('type_of', models.CharField(choices=[('P', 'Потребительский'), ('I', 'Ипотека'), ('A', 'Автокредит')], max_length=1)),
                ('min_scoring', models.FloatField()),
                ('max_scoring', models.FloatField()),
                ('credit_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CreditOrg')),
            ],
        ),
        migrations.CreateModel(
            name='ZayavkiCreditOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_now=True)),
                ('send_dt', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('SENDED', 'Отправлена'), ('ACCEPT', 'Получена'), ('AGREE', 'Одобрена'), ('CANCELED', 'Отказано'), ('ISSUED', 'Выдано')], max_length=10)),
                ('client_anketa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ClientAnketa')),
            ],
        ),
    ]
