# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientanketa',
            options={'verbose_name': 'Анкета клиента'},
        ),
        migrations.AlterModelOptions(
            name='creditorg',
            options={'verbose_name': 'Кредитные организации'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнеры'},
        ),
        migrations.AlterModelOptions(
            name='predlogenie',
            options={'verbose_name': 'Предложения'},
        ),
        migrations.AlterModelOptions(
            name='zayavkicreditorg',
            options={'verbose_name': 'Заявки в кредитную организацию'},
        ),
    ]
