# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180322_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavkicreditorg',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('SENDED', 'Отправлена'), ('ACCEPT', 'Получена'), ('AGREE', 'Одобрена'), ('CANCELED', 'Отказано'), ('ISSUED', 'Выдано')], default='NEW', max_length=10),
        ),
    ]
